#%RAML 1.0 NamedExample
example1:
  
    {
      direction: "Exports",
      year: 2015,
      date: "01/01/2015",
      weekday: "Thursday",
      country: "All",
      commodity: "All",
      transport_Mode: "All",
      measure: "$",
      valuerate: 104000000,
      cumulative: 104000000  
    }

  